package entities;
    
public class ChocoProvidable implements Validable{    
    
    private String providableServiceIdNum; //6 digits
    private String providableServiceDescription; //20 chars
    private String providableServiceFee; //up to $999.99
    
    public String getProvidableServiceIdNum() {
        return providableServiceIdNum;
    }
    
    public void setProvidableServiceIdNum(String providableServiceIdNum) {
        this.providableServiceIdNum = providableServiceIdNum;
    }
    
    public String getProvidableServiceDescription() {
        return providableServiceDescription;
    }
    
    public void setProvidableServiceDescription(String providableServiceDescription) {
        this.providableServiceDescription = providableServiceDescription;
    }
    
    public String getProvidableServiceFee() {
        return providableServiceFee;
    }
    
    public void setProvidableServiceFee(String providableServiceFee) {
        this.providableServiceFee = providableServiceFee;
    }
    
    @Override
    public boolean isValid() {
        if(this.providableServiceIdNum == null || this.providableServiceIdNum.length() != 6) return false;
        for(int i = 0; i < this.providableServiceIdNum.length(); i++){
            if(!Character.isDigit(this.providableServiceIdNum.charAt(i)))
                return false;
        }
        if(this.providableServiceDescription == null || this.providableServiceDescription.length() > 20)
            return false;
//      if(this.providableServiceFee == null || this.providableServiceFee.matches("^\\d{1,3}\\.\\d{2}"))
//          return false;
        return true;
    }
    
} // Class generated by : Benjamin Haos
  // Modified by : Zachary Brunette
  // Last Change by: Zachary Brunette
  // Changes: isValid() completed for review
  //          added providableServiceFee w/ getters and setters