package entities;
    
public class ChocoServiceProvided implements Validable{    
    
    private String chocoServiceProvidedIdNumber; //6 digits
    private String memberNumberServiced; //9 digits
    private String providerNumberServicing; //9 digits
    private String dateServiced; //MM-DD-YYYY
    private String dateServicedRecorded; //MM-DD-YYYY HH:MM:SS
    private String serviceComment; //100 chars
    
    public String getChocoServiceProvidedIdNumber() {
        return chocoServiceProvidedIdNumber;
    }
    
    public void setChocoServiceProvidedIdNumber(String chocoServiceProvidedIdNumber) {
        this.chocoServiceProvidedIdNumber = chocoServiceProvidedIdNumber;
    }
    
    public String getMemberNumberService() {
        return memberNumberServiced;
    }
    
    public void setMemberNumberService(String memberNumberServiced) {
        this.memberNumberServiced = memberNumberServiced;
    }
    
    public String getProviderNumberServicing() {
        return providerNumberServicing;
    }
    
    public void setProviderNumberServicing(String providerNumberServicing) {
        this.providerNumberServicing = providerNumberServicing;
    }
    
    public String getDateServiced() {
        return dateServiced;
    }
    
    public void setDateServiced(String dateServiced) {
        this.dateServiced = dateServiced;
    }
    
    public String getDateServicedRecorded() {
        return dateServicedRecorded;
    }
    
    public void setDateServicedRecorded(String dateServicedRecorded) {
        this.dateServicedRecorded = dateServicedRecorded;
    }
    
    public String getServiceComment() {
        return serviceComment;
    }
    
    public void setServiceComment(String serviceComment) {
        this.serviceComment = serviceComment;
    }
    
    @Override
    public boolean isValid() {
        if(this.chocoServiceProvidedIdNumber == null || this.chocoServiceProvidedIdNumber.length() < 6) return false;
        for(int i = 0; i < this.chocoServiceProvidedIdNumber.length(); i++){
            if(!Character.isDigit(this.chocoServiceProvidedIdNumber.charAt(i)))
                return false;
        }
        if(this.memberNumberServiced == null || this.memberNumberServiced.length() < 9) return false;
        for(int i = 0; i < this.memberNumberServiced.length(); i++){
            if(!Character.isDigit(this.memberNumberServiced.charAt(i)))
                return false;
        }
        if(this.providerNumberServicing == null || this.providerNumberServicing.length() < 9) return false;
        for(int i = 0; i < this.providerNumberServicing.length(); i++){
            if(!Character.isDigit(this.providerNumberServicing.charAt(i)))
                return false;
        }
        if(this.dateServiced == null || !this.dateServiced.matches("^\\d{2}\\-\\d{2}\\-\\d{4}"))
            return false;
        if(this.dateServicedRecorded == null || !this.dateServicedRecorded.matches("^\\d{2}\\-\\d{2}\\-\\d{4}\\s{1}\\d{2}\\:\\d{2}\\:\\d{2}"))
            return false;
        if(this.serviceComment == null || this.serviceComment.length() > 100)
            return false;
        return true;
    }
    
} // Class generated by : Benjamin Haos
  // Modified by : Zachary Brunette
  // Last Change by: Zachary Brunette
  // Changes: isValid() completed for review
