package entities;
    
public class ChocoProvider implements Validable{    
    
    private String providerNumber; //9 digits
    private String providerName; //25 chars
    private String providerStreetAddress; //25 chars
    private String providerCity; //14 chars
    private String providerState; //2 chars
    private long providerZip; //5 digits
    
    public String getProviderNumber() {
        return providerNumber;
    }
    
    public void setProviderNumber(String providerNumber) {
        this.providerNumber = providerNumber;
    }
    
    public String getProviderName() {
        return providerName;
    }
    
    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }
    
    public String getProviderStreetAddress() {
        return providerStreetAddress;
    }
    
    public void setProviderStreetAddress(String providerStreetAddress) {
        this.providerStreetAddress = providerStreetAddress;
    }
    
    public String getProviderCity() {
        return providerCity;
    }
    
    public void setProviderCity(String providerCity) {
        this.providerCity = providerCity;
    }
    
    public String getProviderState() {
        return providerState;
    }
    
    public void setProviderState(String providerState) {
        this.providerState = providerState;
    }
    
    public long getProviderZip() {
        return providerZip;
    }
    
    public void setProviderZip(long providerZip) {
        this.providerZip = providerZip;
    }
    
    @Override
    public boolean isValid() {
        if(this.providerNumber == null || this.providerNumber.length() != 9) return false;
        for(int i = 0; i < this.providerNumber.length(); i++){
            if(!Character.isDigit(this.providerNumber.charAt(i)))
                return false;
        }
        if(this.providerName == null || this.providerName.length() > 25)
            return false;
        if(this.providerStreetAddress == null || this.providerStreetAddress.length() > 25)
            return false;
        if(this.providerCity == null || this.providerCity.length() > 25)
            return false;
        if(this.providerState == null || this. providerState.length() > 25)
            return false;
        if(this.providerZip == 0 || (String.valueOf(this.providerZip)).length() != 5)
            return false;
        for(int i = 0; i < (String.valueOf(this.providerZip)).length(); i++){
            if(!Character.isDigit((String.valueOf(this.providerZip)).charAt(i)))
                return false;
        }
        return true;
    }
    
} // Class generated by : Benjamin Haos
  // Modified by : Zachary Brunette
  // Last Change by: Zachary Brunette
  // Changes: isValid() completed for review
